name: CI

on:
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: kenchan0130/actions-system-info@v1.3.0
        id: system-info
      # Checks-out the repository
      - uses: actions/checkout@v4


      - name: setup llvm 16 repo 
        run: |
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"  | sudo tee -a /etc/apt/sources.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo apt update


      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5


      - run: opam install . --deps-only

      - run: opam exec -- dune build

      - name: Archive sailor
        uses: actions/upload-artifact@v4
        with:
          name: sailor for ${{ steps.system-info.outputs.release }}
          path: |
            _build/install/default/bin/sailor
          if-no-files-found: error
          
      - name: run tests 
        timeout-minutes: 1
        run: opam exec -- dune runtest
